name: 24h-Matrix-Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: 检查代码
        uses: actions/checkout@v3

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: pip install pyTelegramBotAPI requests

      - name: 运行机器人
        # 这里一定要加 || true，防止报错直接让 Action 显示失败但不输出日志
        run: python your_bot.py || true
